### ISSUE TITLE
Table Of Contents - Break 5.A.1 to 5.A.7.B into Non-Voting and Voting Sections [From Robert's Notes]

### ISSUE THREAD

**Issue by IgorPolotai** [rhochgraf21/Constitution#168]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [x] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue: For the Responsibilities section (5.A.1), untab 5.A.1.A, 5.A.2.A, 5.A.2.B, 5.A.3.A, 5.A.7.A, and 5.A.7.B, and make them into 5.A.1, 5.A.2, etc.

**Comment by esoccoli** [comment]
I think it makes more sense to leave it as is, because we specifiy in the bullet points whether they can vote or not. Plus, if we split it into voting and non voting subsections, it would lead to issues with internal consistency bc differing order of directorships (bc chair is non-voting but we always list the directorships with chair first, and imo it desnt make sense to list chair -> secretary -> evals -> etc)

**Comment by esoccoli** [comment]
Decided not to pursue this change
