### ISSUE TITLE
6.B.5 Definition of Batches is vague

### ISSUE THREAD

**Issue by esoccoli** [rhochgraf21/Constitution#65]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Might be useful to clarify things about batch votes, such as:
- When they can be used
- How batches can be proposed
- How batches get approved
- Order of voting on batches (Should it be that we vote to create batch then immediately vote on the batch?)
- What happens if a person is in 2 batches, one of which passes and the other fails

**Comment by mxmeinhold** [comment]
Batches can be used really anywhere. They're proposed by the chair of the vote (who can choose to solicit input), voted on to see if they can occur, and then the whole batch is voted on as one. 

This is a typical practice you might see in other deliberative bodies. My city council will take up items together, and lay items on the table for a single roll call vote at the end (for meetings with lots of votes, roll call is way too slow)

I'd argue the phrasing of a batch is "amend the docket" so the order of voting is up to the person deciding the docket. Practice should generally be "do it now" since we just discussed why we would take these up together.

I think the question of 2 batches is a quirk of how Evals typically uses Batch Votes in Membership Evaluations. One view, I think the normal process is that second batch doesn't include anyone from previous batches, since they've already been voted on. The other more agenda focussed view: When we vote to allow the batch, we're amending the agenda to take a subset of items up together. This means they are no longer in the agenda to be taken up in a separate batch, and the chair of the vote should not propose to do so. (You could, however, propose a series of batch votes, and then propose a batch comprising of them).
